# Generated by Django 3.2.5 on 2021-08-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eungapp', '0002_auto_20210813_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='model',
            field=models.CharField(choices=[('THERM', '온도계'), ('GAS', '가스 센서'), ('AUX', '마이크'), ('ETC', '기타')], default='ETC', max_length=20),
        ),
    ]
