# Generated by Django 3.2.5 on 2021-08-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eungapp', '0003_alter_sensor_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='crydetector',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='model',
            field=models.CharField(choices=[('THERM', '온도계'), ('HUMID', '습도 센서'), ('GAS', '가스 센서'), ('AUX', '마이크'), ('ETC', '기타')], default='ETC', max_length=20),
        ),
    ]
