# Generated by Django 3.2.5 on 2021-08-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eungapp', '0004_auto_20210817_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='location',
            field=models.CharField(choices=[('LIVING_ROOM', '거실'), ('DINING_ROOM', '부엌'), ('BED_ROOM1', '침실1'), ('BED_ROOM2', '침실2'), ('BED_ROOM3', '침실3'), ('ETC', '기타')], default='ETC', max_length=20),
        ),
    ]
