# Generated by Django 3.2.5 on 2021-08-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eungapp', '0005_alter_sensor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='crydetector',
            name='is_cheched',
            field=models.BooleanField(default=False),
        ),
    ]
