# Generated by Django 3.2.5 on 2021-08-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eungapp', '0006_crydetector_is_cheched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crydetector',
            old_name='is_cheched',
            new_name='checked',
        ),
    ]
